modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/BetterDexRewards/issues"

[[mods]]
modId="pokeremoval"
version="2.3.0"
displayName="PokeRemoval Forge"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
updateJSONURL="https://ogn.pixelmonmod.com/update/sm-pr/update.json"
description='''
Removes Pokes
'''

[[dependencies.pokeremoval]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.pokeremoval]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"