modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/BetterDexRewards/issues"

[[mods]]
modId="pokeremoval"
version="2.0.2"
displayName="PokeRemoval Forge"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
updateJSONURL="https://ogn.pixelmonmod.com/update/sm-pr/update.json"
description='''
Removes Pokes
'''

[[dependencies.pokeremoval]]
modId="forge"
mandatory=true
versionRange="[47.1.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.pokeremoval]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"